export enum EnterpriseRoute {
  Workspace = '/workspace',
  Chat = '/workspace/chat',
  Home = '/enterprise/home',
  Platform = '/enterprise/platform',
  PlatformUpdates = '/enterprise/platform-updates',
  Gallery = '/workspace/gallery',
  Agents = '/enterprise/agents',
  Teams = '/enterprise/teams',
  Dashboard = '/enterprise/dashboard',
  ScheduledTasks = '/enterprise/scheduled-tasks',
  Memories = '/enterprise/memories',
  Feedback = '/enterprise/feedback',
  Channels = '/enterprise/channels',
  Knowledge = '/enterprise/knowledge',
  GeneralSkills = '/enterprise/general-skills',
  Skills = '/enterprise/skills',
  Tools = '/enterprise/tools',
  Accounts = '/enterprise/accounts',
  Models = '/enterprise/models',
  RuntimeSettings = '/enterprise/runtime-settings',
  ApiKeyApprovals = '/enterprise/api-key-approvals',
  DecisionAssistant = '/enterprise/decision-assistant',
  AiReviewer = '/enterprise/ai-reviewer',
}
